"""
Patch Rev 1.2 PCB for Rev 2: Move J1 to board edge, D1 away from K1.

Strategy:
- Load clean Rev 1.2 .kicad_pcb (generated by route_pcb.py)
- Delete traces connected to moved components (J1, D1, R6, R7)
- Move those components to new positions
- Re-route affected connections with precise coordinates
- Fix RELAY_NO/RELAY_COM shorting issue

Key routing insight: D+/D- go on B.Cu (hopping over +3V3 at x=5 only),
which frees F.Cu for VBUS with ZERO crossings.

Run with KiCad Python: python.exe patch_pcb_rev2.py
"""

import pcbnew
import os

NM = 1_000_000
PCB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        'production', 'ESP32_Simple_IoT.kicad_pcb')

# Trace widths
PWR_W = 0.5
SIG_W = 0.20
VIA_SIZE = 0.6
VIA_DRILL = 0.3
VIA_PWR_SIZE = 0.8
VIA_PWR_DRILL = 0.4

F_Cu = pcbnew.F_Cu
B_Cu = pcbnew.B_Cu

def mm(val):
    return int(val * NM)

def point(x, y):
    return pcbnew.VECTOR2I(mm(x), mm(y))

def get_pad_pos(board, ref, pad_num):
    for fp in board.GetFootprints():
        if fp.GetReference() == ref:
            for pad in fp.Pads():
                if pad.GetNumber() == pad_num:
                    pos = pad.GetPosition()
                    return (pos.x / NM, pos.y / NM)
    return None

def add_track(board, net, layer, width, x1, y1, x2, y2):
    if abs(x1 - x2) < 0.001 and abs(y1 - y2) < 0.001:
        return
    track = pcbnew.PCB_TRACK(board)
    track.SetStart(point(x1, y1))
    track.SetEnd(point(x2, y2))
    track.SetWidth(mm(width))
    track.SetLayer(layer)
    track.SetNet(net)
    board.Add(track)

def add_via(board, net, x, y, size=VIA_SIZE, drill=VIA_DRILL):
    via = pcbnew.PCB_VIA(board)
    via.SetPosition(point(x, y))
    via.SetViaType(pcbnew.VIATYPE_THROUGH)
    via.SetWidth(mm(size))
    via.SetDrill(mm(drill))
    via.SetNet(net)
    board.Add(via)

def route_polyline(board, net, layer, width, points, chamfer=0.5):
    if not points or len(points) < 2:
        return
    new_points = [points[0]]
    for i in range(1, len(points) - 1):
        p_prev, p_curr, p_next = points[i-1], points[i], points[i+1]
        v1 = (p_prev[0] - p_curr[0], p_prev[1] - p_curr[1])
        v2 = (p_next[0] - p_curr[0], p_next[1] - p_curr[1])
        l1 = (v1[0]**2 + v1[1]**2)**0.5
        l2 = (v2[0]**2 + v2[1]**2)**0.5
        actual_chamfer = min(chamfer, l1 * 0.4, l2 * 0.4)
        if actual_chamfer > 0.1:
            p1 = (p_curr[0] + v1[0]/l1 * actual_chamfer, p_curr[1] + v1[1]/l1 * actual_chamfer)
            p2 = (p_curr[0] + v2[0]/l2 * actual_chamfer, p_curr[1] + v2[1]/l2 * actual_chamfer)
            new_points.extend([p1, p2])
        else:
            new_points.append(p_curr)
    new_points.append(points[-1])
    for i in range(len(new_points) - 1):
        x1, y1 = new_points[i]
        x2, y2 = new_points[i + 1]
        add_track(board, net, layer, width, x1, y1, x2, y2)


# ============================================================
# STEP 1: Load PCB and collect old pad positions
# ============================================================

print("Loading Rev 1.2 PCB...")
board = pcbnew.LoadBoard(PCB_PATH)

# Get net objects
net_map = {}
for name, netinfo in board.GetNetInfo().NetsByName().items():
    net_map[str(name)] = netinfo

def net(name):
    return net_map[name]

# Collect OLD pad positions for components we're moving
old_pads = {}
for ref in ['J1', 'D1', 'R6', 'R7']:
    for fp in board.GetFootprints():
        if fp.GetReference() == ref:
            for pad in fp.Pads():
                num = pad.GetNumber()
                pos = pad.GetPosition()
                old_pads.setdefault(ref, {})[num] = (pos.x / NM, pos.y / NM)

# Also collect RELAY_NO pad positions for the fix
for fp in board.GetFootprints():
    if fp.GetReference() == 'K1':
        for pad in fp.Pads():
            if pad.GetNumber() == '4':
                old_pads.setdefault('K1', {})['4'] = (pad.GetPosition().x / NM, pad.GetPosition().y / NM)

print(f"  Collected {sum(len(v) for v in old_pads.values())} pad positions from {len(old_pads)} components")

# ============================================================
# STEP 2: Delete traces connected to moved components
# ============================================================

print("Deleting traces connected to moved components...")

# Collect all old pad positions as a set of (x, y) points
old_positions = set()
for ref, pads in old_pads.items():
    for num, pos in pads.items():
        old_positions.add(pos)

# Also need to delete: J1 VBUS secondary route, GND stubs, CC routes
# Delete any track/via within 1mm of any old pad position
RADIUS = 2.0  # mm — wider to catch old stubs and GND vias near moved pads
tracks_to_delete = []
for track in board.GetTracks():
    pos = track.GetPosition()
    tx, ty = pos.x / NM, pos.y / NM

    # Check start and end for tracks
    if hasattr(track, 'GetStart'):
        sx, sy = track.GetStart().x / NM, track.GetStart().y / NM
        ex, ey = track.GetEnd().x / NM, track.GetEnd().y / NM
        for ox, oy in old_positions:
            if ((sx - ox)**2 + (sy - oy)**2)**0.5 < RADIUS or \
               ((ex - ox)**2 + (ey - oy)**2)**0.5 < RADIUS:
                tracks_to_delete.append(track)
                break
    else:
        # Via - check position
        for ox, oy in old_positions:
            if ((tx - ox)**2 + (ty - oy)**2)**0.5 < RADIUS:
                tracks_to_delete.append(track)
                break

# Also delete RELAY_NO tracks (to fix shorting with RELAY_COM at y=52)
for track in board.GetTracks():
    if track.GetNet().GetNetname() == 'RELAY_NO':
        tracks_to_delete.append(track)

# Delete GND stitch vias that conflict with moved components
for track in board.GetTracks():
    if type(track).__name__ == 'PCB_VIA' and track.GetNet().GetNetname() == 'GND':
        tx, ty = track.GetPosition().x / NM, track.GetPosition().y / NM
        # (25, 56) and (30, 56) — too close to K1:2 (+5V)
        if abs(ty - 56) < 0.5 and (abs(tx - 25) < 0.5 or abs(tx - 30) < 0.5):
            tracks_to_delete.append(track)
        # (40, 55) — conflicts with new D1 position
        if abs(tx - 40) < 1 and abs(ty - 55) < 1:
            tracks_to_delete.append(track)

# Delete old CC/GND traces and vias in the old J1/R6/R7 area (x<12, y=20-35)
for track in board.GetTracks():
    net_name = track.GetNet().GetNetname()
    if hasattr(track, 'GetStart'):
        sx, sy = track.GetStart().x / NM, track.GetStart().y / NM
        ex, ey = track.GetEnd().x / NM, track.GetEnd().y / NM
        # Delete CC1/CC2 traces in old routing area
        if net_name in ('CC1', 'CC2') and (sx < 12 or ex < 12):
            tracks_to_delete.append(track)
        # Delete GND traces/vias in old J1 area that will conflict with VBUS
        if net_name == 'GND' and sx < 12 and sy > 20 and sy < 35 and ex < 12 and ey > 20 and ey < 35:
            tracks_to_delete.append(track)
    else:
        tx, ty = track.GetPosition().x / NM, track.GetPosition().y / NM
        if net_name in ('CC1', 'CC2') and tx < 12:
            tracks_to_delete.append(track)
        # Delete GND vias in old J1 area (these conflict with new VBUS horizontals)
        if net_name == 'GND' and tx < 12 and ty > 20 and ty < 35:
            tracks_to_delete.append(track)

# Also delete the GND zone bridge (between old power corridors)
# These are at (6.2, 46) and (3.8, 46) - delete tracks/vias near there
for track in board.GetTracks():
    if hasattr(track, 'GetStart'):
        sx, sy = track.GetStart().x / NM, track.GetStart().y / NM
        ex, ey = track.GetEnd().x / NM, track.GetEnd().y / NM
        if (abs(sy - 46) < 0.5 and abs(ey - 46) < 0.5 and
            min(sx, ex) < 5 and max(sx, ex) > 5 and
            track.GetNet().GetNetname() == 'GND'):
            tracks_to_delete.append(track)
    else:
        tx, ty = track.GetPosition().x / NM, track.GetPosition().y / NM
        if abs(ty - 46) < 0.5 and (abs(tx - 6.2) < 0.3 or abs(tx - 3.8) < 0.3):
            if track.GetNet().GetNetname() == 'GND':
                tracks_to_delete.append(track)

# Deduplicate and delete
deleted = set()
for track in tracks_to_delete:
    tid = id(track)
    if tid not in deleted:
        board.Remove(track)
        deleted.add(tid)

print(f"  Deleted {len(deleted)} tracks/vias")

# ============================================================
# STEP 3: Move components
# ============================================================

print("Moving components...")

moves = {
    'J1': (4, 30, 90),      # Left board edge, rotated 90°
    'D1': (29, 55, 0),       # Pad1@(29,55), Pad2@(~39,55) — 1mm further from GND zone fill
    'R6': (2, 38, 90),       # South of J1 for CC1
    'R7': (2, 22, 90),       # North of J1 for CC2
}

for fp in board.GetFootprints():
    ref = fp.GetReference()
    if ref in moves:
        x, y, rot = moves[ref]
        fp.SetPosition(point(x, y))
        fp.SetOrientationDegrees(rot)
        print(f"  {ref}: moved to ({x}, {y}) rot={rot}")

# ============================================================
# STEP 4: Get new pad positions
# ============================================================

print("Reading new pad positions...")

def p(ref, pad_num):
    pos = get_pad_pos(board, ref, pad_num)
    if pos is None:
        print(f"  WARNING: {ref}:{pad_num} not found!")
        return (0, 0)
    return pos

# Print key positions
for ref, pad_num, label in [
    ('J1', 'A4', 'VBUS'), ('J1', 'A6', 'D+'), ('J1', 'A7', 'D-'),
    ('J1', 'A5', 'CC1'), ('J1', 'B5', 'CC2'), ('J1', 'A9', 'VBUS2'),
    ('J1', 'A1', 'GND'), ('J1', 'A12', 'GND'), ('J1', 'A8', 'GND'),
    ('J1', 'B8', 'GND'), ('J1', 'B12', 'GND'),
    ('D1', '1', '+5V'), ('D1', '2', 'RELAY_COIL'),
    ('R6', '1', 'CC1'), ('R6', '2', 'GND'),
    ('R7', '1', 'CC2'), ('R7', '2', 'GND'),
    ('K1', '4', 'RELAY_NO'),
]:
    pos = p(ref, pad_num)
    print(f"  {ref}:{pad_num} ({label}) = ({pos[0]:.2f}, {pos[1]:.2f})")

# ============================================================
# STEP 5: Route all affected connections
# ============================================================

print("Routing new connections...")

# --- VBUS: J1:A4 -> FB1:1 (all F.Cu, no hops needed!) ---
p_vbus = p('J1', 'A4')
p_fb1 = p('FB1', '1')
route_polyline(board, net('VBUS'), F_Cu, PWR_W, [
    p_vbus,                        # ~(0.32, 32.4)
    (12, p_vbus[1]),            # Right to VBUS vertical
    (12, p_fb1[1]),             # North to FB1 y=8
    p_fb1,                         # Right to FB1
])
print("  VBUS: J1:A4 -> FB1:1 (all F.Cu)")

# --- VBUS: J1:A9 -> join vertical corridor ---
p_a9 = p('J1', 'A9')
route_polyline(board, net('VBUS'), F_Cu, PWR_W, [
    p_a9,                          # ~(0.32, 27.6)
    (12, p_a9[1]),              # Right to VBUS vertical
])
print("  VBUS: J1:A9 -> corridor")

# --- USB_D+: J1:A6 -> U3:4 (all B.Cu, zero hops!) ---
# South at x=2 to y=55 (below ALL relay/power traces), east to x=7,
# north to y=44 (where +3V3/+5V are on F.Cu), east to x=12, via to F.Cu
p_dp = p('J1', 'A6')
p_dp_u = p('U3', '4')
add_track(board, net('USB_D+'), F_Cu, SIG_W, p_dp[0], p_dp[1], 2, p_dp[1])
add_via(board, net('USB_D+'), 2, p_dp[1])
route_polyline(board, net('USB_D+'), B_Cu, SIG_W, [
    (2, p_dp[1]),                  # ~(2, 30.25)
    (2, 55),                       # South to y=55 (below relay area)
    (7, 55),                       # Right to x=7 (left of +5V@x=8)
    (7, p_dp_u[1]),               # North to y=44 (corridors on F.Cu here)
    (12, p_dp_u[1]),              # Right to x=12
])
add_via(board, net('USB_D+'), 12, p_dp_u[1])
add_track(board, net('USB_D+'), F_Cu, SIG_W, 12, p_dp_u[1], p_dp_u[0], p_dp_u[1])
print("  USB_D+: J1:A6 -> U3:4 (all B.Cu, zero hops)")

# --- USB_D-: J1:A7 -> U3:5 (B.Cu, 1 hop over RELAY_COIL at y=50) ---
# South at x=2.8 to y=57 (below relay), east to x=14 (east of +5V@x=13),
# north at x=14 with F.Cu hop over RELAY_COIL B.Cu at y=50
p_dm = p('J1', 'A7')
p_dm_u = p('U3', '5')
add_track(board, net('USB_D-'), F_Cu, SIG_W, p_dm[0], p_dm[1], 2.8, p_dm[1])
add_via(board, net('USB_D-'), 2.8, p_dm[1])
route_polyline(board, net('USB_D-'), B_Cu, SIG_W, [
    (2.8, p_dm[1]),                # ~(2.8, 29.75)
    (2.8, 57),                     # South to y=57 (below ALL relay/power)
    (14, 57),                      # Right to x=14 (all corridors ended)
    (14, 51),                      # North to y=51 (before RELAY_COIL at y=50)
])
# F.Cu hop over RELAY_COIL B.Cu at y=50
add_via(board, net('USB_D-'), 14, 51)
add_track(board, net('USB_D-'), F_Cu, SIG_W, 14, 51, 14, 49)
add_via(board, net('USB_D-'), 14, 49)
# B.Cu north to U3:5 y
route_polyline(board, net('USB_D-'), B_Cu, SIG_W, [
    (14, 49),                      # Resume B.Cu past RELAY_COIL
    (14, p_dm_u[1]),              # North to y=44.5
])
add_via(board, net('USB_D-'), 14, p_dm_u[1])
add_track(board, net('USB_D-'), F_Cu, SIG_W, 14, p_dm_u[1], p_dm_u[0], p_dm_u[1])
print("  USB_D-: J1:A7 -> U3:5 (B.Cu, 1 hop over RELAY_COIL)")

# --- CC1: J1:A5 -> R6:1 (B.Cu hop over VBUS at y=32.4) ---
p_cc1 = p('J1', 'A5')
p_r6_1 = p('R6', '1')
p_r6_2 = p('R6', '2')
# F.Cu stub right to x=3.5 (avoids D- via at x=2.8 and GND B8 pad)
add_track(board, net('CC1'), F_Cu, SIG_W, p_cc1[0], p_cc1[1], 3.5, p_cc1[1])
add_via(board, net('CC1'), 3.5, p_cc1[1])
add_track(board, net('CC1'), B_Cu, SIG_W, 3.5, p_cc1[1], 3.5, 35)  # Past VBUS@32.4
add_via(board, net('CC1'), 3.5, 35)
# F.Cu: approach R6:1 from right side to avoid crossing R6:2 GND pad
route_polyline(board, net('CC1'), F_Cu, SIG_W, [
    (3.5, 35),
    (3.5, p_r6_1[1]),            # South to R6:1 y
    p_r6_1,                        # Left to R6:1
])
# R6:2 GND via — route left (away from CC1 at x=3)
add_track(board, net('GND'), F_Cu, SIG_W, p_r6_2[0], p_r6_2[1], p_r6_2[0] - 1, p_r6_2[1])
add_via(board, net('GND'), p_r6_2[0] - 1, p_r6_2[1])
print("  CC1: J1:A5 -> R6:1 (B.Cu hop over VBUS)")

# --- CC2: J1:B5 -> R7:1 (B.Cu hop over VBUS at y=27.6) ---
p_cc2 = p('J1', 'B5')
p_r7_1 = p('R7', '1')
p_r7_2 = p('R7', '2')
add_track(board, net('CC2'), F_Cu, SIG_W, p_cc2[0], p_cc2[1], 3, p_cc2[1])
add_via(board, net('CC2'), 3, p_cc2[1])
add_track(board, net('CC2'), B_Cu, SIG_W, 3, p_cc2[1], 3, 26)  # Past VBUS@27.6
add_via(board, net('CC2'), 3, 26)
add_track(board, net('CC2'), F_Cu, SIG_W, 3, 26, p_r7_1[0], p_r7_1[1])
# R7:2 GND via
add_track(board, net('GND'), F_Cu, SIG_W, p_r7_2[0], p_r7_2[1], p_r7_2[0], p_r7_2[1] - 1)
add_via(board, net('GND'), p_r7_2[0], p_r7_2[1] - 1)
print("  CC2: J1:B5 -> R7:1 (B.Cu hop over VBUS)")

# --- J1 GND pads: route right to vias at x=6 ---
# GND vias at x=9 (well past +5V B.Cu@x=8, clear of J1 body ending ~x=7.7)
# Stagger x to avoid via-to-via overlap for pads at similar y
gnd_via_plan = [
    ('A1',  9.0),   # y≈33.2
    ('A12', 9.0),   # y≈26.8
    ('B12', 9.5),   # y≈33.2 (stagger from A1)
    ('A8',  9.0),   # y≈28.75
    ('B8',  9.5),   # y≈31.75
]
for pad_name, via_x in gnd_via_plan:
    pos = p('J1', pad_name)
    add_track(board, net('GND'), F_Cu, SIG_W, pos[0], pos[1], via_x, pos[1])
    add_via(board, net('GND'), via_x, pos[1])
print("  J1 GND: 5 pads -> vias at x=6-6.5")

# --- D1: +5V from K1:2 and RELAY_COIL to K1:1 ---
p_d1_1 = p('D1', '1')    # +5V (cathode)
p_d1_2 = p('D1', '2')    # RELAY_COIL (anode)
p_k1_1 = p('K1', '1')    # RELAY_COIL
p_k1_2 = p('K1', '2')    # +5V

# +5V: K1:2 -> D1:1 (local F.Cu route)
route_polyline(board, net('+5V'), F_Cu, PWR_W, [
    p_k1_2,                        # K1:2 (+5V)
    (p_d1_1[0], p_k1_2[1]),      # East to D1:1 x
    p_d1_1,                        # South to D1:1
])
print("  +5V: K1:2 -> D1:1 (F.Cu)")

# RELAY_COIL: D1:2 -> K1:1 via B.Cu around relay
d1_via = (p_d1_2[0], p_d1_2[1] + 1.5)
add_track(board, net('RELAY_COIL'), F_Cu, SIG_W, p_d1_2[0], p_d1_2[1], d1_via[0], d1_via[1])
add_via(board, net('RELAY_COIL'), d1_via[0], d1_via[1])
route_polyline(board, net('RELAY_COIL'), B_Cu, SIG_W, [
    d1_via,
    (d1_via[0], 58.5),            # South past relay
    (p_k1_1[0], 58.5),           # Left to K1:1 x
    (p_k1_1[0], p_k1_1[1] + 1),  # Up near K1:1
])
add_via(board, net('RELAY_COIL'), p_k1_1[0], p_k1_1[1] + 1)
add_track(board, net('RELAY_COIL'), F_Cu, SIG_W, p_k1_1[0], p_k1_1[1] + 1, p_k1_1[0], p_k1_1[1])
print("  RELAY_COIL: D1:2 -> K1:1 (B.Cu around relay)")

# --- Fix RELAY_NO: reroute at y=49 to avoid RELAY_COM at y=52 ---
p_k1_4 = p('K1', '4')    # RELAY_NO
p_j2_2 = p('J2', '2')    # Terminal
route_polyline(board, net('RELAY_NO'), F_Cu, PWR_W, [
    p_k1_4,                        # K1:4 RELAY_NO
    (p_k1_4[0], 49),             # South to y=49
    (p_j2_2[0], 49),             # Right to J2:2 x
    p_j2_2,                        # South to J2:2
])
print("  RELAY_NO: K1:4 -> J2:2 (at y=49, avoids RELAY_COM at y=52)")

# --- Fix +3V3/GND short: detour +3V3 B.Cu around J1 shield tabs ---
# Shield tabs at (5.08, 25.68) and (5.08, 34.32) overlap +3V3 B.Cu at x=5
# Detour to x=4.2 (SIG_W) between y=24-36, then rejoin x=5
# --- Fix +3V3/GND short: detour around J1 shield tabs at (5.08, 25.68/34.32) ---
# Delete ALL +3V3 B.Cu in the shield tab zone and rebuild with x=4.2 detour
print("  Fixing +3V3 detour around J1 shield tabs...")
tracks_3v3_delete = []
for track in board.GetTracks():
    if not hasattr(track, 'GetStart'):
        continue
    if track.GetNet().GetNetname() != '+3V3' or track.GetLayer() != B_Cu:
        continue
    sx, sy = track.GetStart().x / NM, track.GetStart().y / NM
    ex, ey = track.GetEnd().x / NM, track.GetEnd().y / NM
    # Delete VERTICAL +3V3 B.Cu segments at x=4-6 passing y=20-42
    both_in_x = (3.5 < sx < 6) and (3.5 < ex < 6)
    spans_y = min(sy, ey) < 38 and max(sy, ey) > 20
    if both_in_x and spans_y:
        tracks_3v3_delete.append(track)
for t in tracks_3v3_delete:
    board.Remove(t)
print(f"    Deleted {len(tracks_3v3_delete)} +3V3 B.Cu segments")
# Rebuild: x=5 from y=16 to y=22, detour to x=4.2 at y=22-36, back to x=5, continue to y=42
add_track(board, net('+3V3'), B_Cu, PWR_W, 5, 16, 5, 22)
add_track(board, net('+3V3'), B_Cu, SIG_W, 5, 22, 4.2, 22)
add_track(board, net('+3V3'), B_Cu, SIG_W, 4.2, 22, 4.2, 38)
add_track(board, net('+3V3'), B_Cu, SIG_W, 4.2, 38, 5, 38)
add_track(board, net('+3V3'), B_Cu, PWR_W, 5, 38, 5, 42)
print("  +3V3: detoured x=5→x=4.2 between y=22-38 (clears shield tabs)")

# --- Clean up orphan/dangling traces ---
print("  Cleaning up orphan traces...")
orphan_count = 0
for track in list(board.GetTracks()):
    net_name = track.GetNet().GetNetname()
    if hasattr(track, 'GetStart'):
        sx, sy = track.GetStart().x / NM, track.GetStart().y / NM
        ex, ey = track.GetEnd().x / NM, track.GetEnd().y / NM
        # Old +5V relay corridor remnant at x≈8, y>46
        if net_name == '+5V' and track.GetLayer() == B_Cu:
            if abs(sx - 8) < 1 and sy > 46 and abs(ex - 8) < 1:
                board.Remove(track); orphan_count += 1; continue
            if abs(ex - 8) < 1 and ey > 46 and abs(sx - 8) < 1:
                board.Remove(track); orphan_count += 1; continue
        # Old +5V F.Cu approach stub near (11, 48-49)
        if net_name == '+5V' and track.GetLayer() == F_Cu:
            if 10 < sx < 12 and 47 < sy < 50 and 10 < ex < 12:
                board.Remove(track); orphan_count += 1; continue
        # Old RELAY_COIL F.Cu stub near (20, 50)
        if net_name == 'RELAY_COIL' and track.GetLayer() == F_Cu:
            if 19 < sx < 23 and 49 < sy < 52:
                board.Remove(track); orphan_count += 1; continue
            if 19 < ex < 23 and 49 < ey < 52:
                board.Remove(track); orphan_count += 1; continue
    else:
        tx, ty = track.GetPosition().x / NM, track.GetPosition().y / NM
        # Old USB_D- via at (7, 29.3)
        if net_name == 'USB_D-' and abs(tx - 7) < 0.5 and abs(ty - 29.3) < 0.5:
            board.Remove(track); orphan_count += 1; continue
        # Old +5V vias in relay corridor (x≈8, y>43)
        if net_name == '+5V' and abs(tx - 8) < 1 and ty > 43:
            board.Remove(track); orphan_count += 1; continue
        # Old RELAY_COIL vias near (20, 50)
        if net_name == 'RELAY_COIL' and 19 < tx < 23 and 49 < ty < 52:
            board.Remove(track); orphan_count += 1; continue
print(f"    Removed {orphan_count} orphan tracks/vias")

# ============================================================
# STEP 6: Update NPTH keepout zones
# ============================================================

print("Updating NPTH keepout zones...")
# Old J1 NPTHs were at ~(3.11, 27.395) and (8.89, 27.395)
# New J1 NPTHs at ~(1.4, 32.9) and (1.4, 27.1) after 90° rotation at (4, 30)
# Keepout zones are copper pour exclusions — they'll be recalculated by zone fill
# No explicit action needed since we're refilling zones

# ============================================================
# STEP 7: Fill zones and save
# ============================================================

print("Filling zones...")
filler = pcbnew.ZONE_FILLER(board)
filler.Fill(board.Zones())

print(f"Saving to {PCB_PATH}...")
pcbnew.SaveBoard(PCB_PATH, board)

# Summary
tracks = board.GetTracks()
n_tracks = sum(1 for t in tracks if type(t).__name__ == 'PCB_TRACK')
n_vias = sum(1 for t in tracks if type(t).__name__ == 'PCB_VIA')
print(f"\n{'=' * 60}")
print(f"PCB PATCH COMPLETE")
print(f"  Moved: J1 to (4,30,90°), D1 to (42,55), R6 to (2,38), R7 to (2,22)")
print(f"  Tracks: {n_tracks}, Vias: {n_vias}")
print(f"  Fixed: USB-C at board edge, D1 clear of K1, RELAY_NO routing")
print(f"{'=' * 60}")
